### ISSUE TITLE
Parsing as JSON won't work for every resource

### ISSUE THREAD

**Issue by developerdavi** [paxful/sdk-js#9]
Sometimes, we don't really want to receive a json back from the API. That's the case when we are fetching an attachment from a trade. We expect receiving an arraybuffer, and if you try to parse that data as a JSON, an exception will be thrown.

Endpoint: `/paxful/v1/trade-chat/image`

Exception:

![exception](https://user-images.githubusercontent.com/31714350/135130971-19be635d-6bda-43e6-96b3-e8f41688d9c9.png)

The issue:

https://github.com/paxful/sdk-js/blob/74bf7907acd14228764594f5209cf7bb18df29b3/src/commands/Invoke.ts#L43

That's how we were handling it, before using the new SDK:

![correct example](https://user-images.githubusercontent.com/31714350/135131582-8d1c4a8e-dd1c-4db4-8918-badfe7eba0fb.png)

In the case above, `this.api` is an `AxiosInstance`.

**Comment by Bakrog** [comment]
Yes, resources returning array buffers are not going to be covered by current implementation. I'm going to prepare a fix for current problem.
I'm going to fix it tonight.

**Comment by Bakrog** [comment]
I added a test to reproduce the error: https://github.com/paxful/sdk-js/pull/10/checks?check_run_id=3735790248

**Comment by developerdavi** [comment]
Awesome! Thank you for your fast response.
